### ISSUE TITLE
Exception: Invalid objective: rmse

### ISSUE THREAD

**Issue by tengpeng** [jocicmarko/kaggle-dsb2-keras#1]
When I was running `train.py`, I got

```
Traceback (most recent call last):
  File "train.py", line 147, in <module>
    train()
  File "train.py", line 52, in train
    model_systole = get_model()
  File "/kaggle-ndsb2/model.py", line 52, in get_model
    model.compile(optimizer=adam, loss='rmse')
  File "/home/pt/anaconda2/lib/python2.7/site-packages/keras/models.py", line 460, in compile
    self.loss = objectives.get(loss)
  File "/home/pt/anaconda2/lib/python2.7/site-packages/keras/objectives.py", line 62, in get
    return get_from_module(identifier, globals(), 'objective')
  File "/home/pt/anaconda2/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 14, in get_from_module
    str(identifier))
Exception: Invalid objective: rmse

```

**Comment by tengpeng** [comment]
I did not change anything in the code, including the loss function.

**Comment by jocicmarko** [comment]
RMSE loss function is removed in the newest version of Keras.
I just updated the code to include RMSE as a custom loss function - check `model.py`.

**Comment by tengpeng** [comment]
Solved. Thanks!
